### ISSUE TITLE
I am looking forward to your code. When will it be released?

### ISSUE THREAD

**Issue by KANGX99** [ruocwang/dpo-diffusion#1]
@ruocwang

**Comment by shudong-zhang** [comment]
same question.

**Comment by ruocwang** [comment]
Hi guys,

Sorry for the delay. I am mostly done with organizing the codebase but I've been busy with a couple of other errands. I expect to push them out before our poster session on Thursday next week. Thank you for your patience.

**Comment by KANGX99** [comment]
That's great！😊

**Comment by patrolli** [comment]
Hi @ruocwang , i am still looking forward for the codes, is there any schedule update for it? Thanks a lot

**Comment by Mowenyii** [comment]
+1

**Comment by ruocwang** [comment]
Hi my fellows, I will wrap everything up no matter what right after NeurIPS rebuttal ends (Aug 7). That's a promise. Sorry for keeping you waiting!

**Comment by ruocwang** [comment]
Hi friends, it's finally done! Thank you so much for your patience. Hopefully, I made the docs detailed enough to save you some trouble getting everything up and running, as a small compensation:)

**Comment by KANGX99** [comment]
Hey @ruocwang,
Just wanted to say a huge thanks for open-sourcing your code! It's been super helpful for the community.
Thanks again for your impressive work! 😊
